name: cesm-exp
channels:
  - conda-forge
  - nodefaults
dependencies:
  - bokeh
  - bottleneck
  - cartopy
  - cf_units
  - cftime
  - click==8.0.2
  - cmocean
  - codecov
  - conda-lock
  - dask
  - dask-jobqueue
  - dask-mpi
  - datashader
  - distributed
  - eofs
  - esmpy
  - holoviews
  - intake
  - intake-esm
  - intake-xarray
  - ipykernel
  - jupyter
  - jupyter-book
  - jupyter-server-proxy
  - jupyter_client==6.1.12
  - jupyter_contrib_nbextensions
  - jupyterlab
  - matplotlib
  - myst-nb
  - nb_conda_kernels
  - nbformat
  - nbsphinx
  - nc-time-axis
  - ncar-jobqueue
  - netcdf4
  - numba
  - numpy
  - numpydoc
  - pandas
  - panel
  - papermill
  - pint
  - pip
  - pop-tools
  - pre-commit
  - pytest
  - pytest-cov
  - python
  - scipy
  - seaborn
  - seawater
  - statsmodels
  - toolz
  - tqdm
  - watermark
  - xarray
  - xcollection
  - xesmf
  - xgcm
  - xhistogram
  - xrft
  - zarr
